### ISSUE TITLE
(Tracking Issue) Refactor SystemState

### ISSUE THREAD

**Issue by kylestach** [RoboJackets/robocup-software#1301]
We have as a stated goal to refactor Processor, but before we take a look at our logic we need to work on our data representation. Currently, all data is passed around in SystemState without any clear "ownership" over individual fields. For example, gameplay code, motion planning, and radio all read and write to fields in the `Robot` class.

Address this by splitting SystemState up into several smaller data structures that are more "atomic" (i.e. written as a unit, so WorldState written by vision filter, RobotStatus written by radio, RobotCommands written by gameplay, etc. with a Logger and DebugDrawer that are accessible everywhere), with each module containing a pointer to a Context that contains them all (instead of a SystemState pointer).

This doesn't necessarily fix all of our issues (we still have shared mutable state) but it clarifies who is responsible for which data and make each of the modules a little bit more independent, and prepares us well for a long-term move to ROS if that's the direction we want to go.

Current plan of attack (in chronological order):

- [x] Add a `Context` struct containing only `SystemState`, propagate a `Context` through the tree. **Done: #1303**
- [x] Move `GameState` from `SystemState` into `Context`. **Done: #1304**
- [x] Break out debug-drawing capability from `SystemState` into `DebugDrawer`. **Done: #1305**
- [x] ~Make Python-side Robot class to maintain existing gameplay API by wrapping reads/writes from structs (start by just forwarding calls to the old `OurRobot` class)~
- [x] Break out `WorldState` (ball and robot positions and velocities) **Review: #1333**
- [x] Break out `RobotPath`
- [x] Break out `RobotStatus` for robot status reports from radio
- [x] Break out `RobotIntent` for the goals set by the gameplay module
- [x] Break out `RobotCommand` for the final commands ready to be sent to the radio, with a function to generate a radio packet and a proto
- [x] Move configuration parameters into context instead of making it totally global
- [ ] **(Ongoing)** make individual parts of the code take in one struct and return another instead of directly mutating values in the `SystemState`: for example, a path planner should take in a `WorldState` and `RobotIntent` and produce a `RobotPath`. The following is an in-progress list of places we need to do this; if you think of something that needs to be added to this list, comment or DM me.
  - [ ] Planner: `(WorldState, RobotIntent) -> RobotPath`
  - [x] Radio: `RobotCommand -> (network) -> RobotStatus`
  - [x] Motion control/trajectory follower: `(RobotCommand, RobotPath, WorldState) -> RobotIntent`
  - [x] Vision filter: `RobotCommand -> WorldState`
  - [x] Joystick: `void -> RobotIntent`

**Comment by kylestach** [comment]
Design document at https://docs.google.com/document/d/1PtYyQZw4U_mi9_kKPo3MaGdwrDQBDLlUuKgejMJbOL4/edit#heading=h.ra68ncnru5q0.

**Comment by kylestach** [comment]
Looking at this a little more, I think it makes sense to keep Robot a C++-side class for now and just shell out as much of its functionality as possible. That marks one additional item off the list.

**Comment by kylestach** [comment]
The remainder of this issue is covered by #1424
