### ISSUE TITLE
(Tracking issue) Refactor Processor into modules

### ISSUE THREAD

**Issue by kylestach** [RoboJackets/robocup-software#1329]
# Description
Currently, Processor has a lot of extra logic to iterate over robots and apply modules to each robot, etc. We want to move logic out of processor, so we will be introducing modules. Each module will be run in sequence (Processor will contain a `vector<unique_ptr<Module>>`) and will own a context pointer (so it will know how to operate).

## Requirements

 - [x] Module base class (#1330)
 - [x] Motion control module (#1330)
 - [x] Vision filter module
 - [x] Vision receiver module (#1332)
 - [x] Radio module (#1400)
 - [x] Gameplay module (trivial)
 - [x] Joysticks (see #1325)
 - [x] Referee module (trivial)
 - [x] Logger module

## Design

[Link to design document](https://docs.google.com/document/d/13LJ-HotI7wjp8G1xqDhcK5y4MAMSmWZyr55kbajW1qw/edit#heading=h.yvwkw0oatlpt)

Also, see #1303 for information about how we plan to pass information between modules.

**Comment by jpfeltracco** [comment]
This might be dumb, feel free to ignore 😉. But I got a bit confused by the term "Module" at first and I think others might too in the future. C++ has had "modules" support coming out for a while (should be slated for C++20 now).

Any other terms that might prevent overloading "modules"? "Manager", "handler", "thingythatdoesstuff"?

**Comment by kylestach** [comment]
@jpfeltracco that's a fair point - thinking about it, that's going to be one of those things that causes people to curse my name forever post-2020.

I'm not sure about Manager, I don't really think that captures it. `Runnable` might work (or if we really want to go all out on the Processor theme, `Processable` :stuck_out_tongue_winking_eye: ) - although the -able suffix feels sort of Java-y to me.

**Comment by oswinso** [comment]
How about.... `Node`? 😋

**Comment by kylestach** [comment]
`Subsystem` maybe? A little bit odd but no conflicts with existing terminology...

**Comment by kylestach** [comment]
Update: discussed offline, we're going with `Node`.
